package com.controller;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.metadata.Usage;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.template.st.StTemplateRenderer;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

@Slf4j
@RestController
@RequiredArgsConstructor
public class MyController {

    private final ChatClient chatClient;
    private final ChatModel chatModel;

    // This Get End point process User message
    @GetMapping("/ai")
    public String getResponse(@RequestParam String userQuery){
        return chatClient.prompt()
                .user(userQuery)
                .call() // Send Request to AI model
                .content(); // return the AI model response as a string
    }

    /* This End point uses ChatResponse
    getResult() : Retrieves the result of the AI model.
    getOutput() : Retrieves the output generated by the AI model
    getText() : Get the content of the message
    getUsage() : Returns AI provider specific metadata on API usage */
    @GetMapping("/response")
    public String getChatResponse(@RequestParam String userResponse){
                ChatResponse res = chatClient.prompt().user(userResponse).call().chatResponse();

                Usage usage = res.getMetadata().getUsage();
                log.info("Input Tokens: {}", usage.getPromptTokens());
                log.info("Output Tokens: {}", usage.getCompletionTokens());
                log.info("Total Tokens: {}", usage.getTotalTokens());
                log.info("Model: {}", res.getMetadata().getModel());
                log.info("Finish Reason: {}", res.getResult().getMetadata().getFinishReason());

        return res.getResult().getOutput().getText();
    }

    /*In this endpoint. I am using the concept of Prompt Template and replacing variable at runtime with custom
    sign <, >

    `.text() :This method sets the main text content for the user's message,
      which can include dynamic template placeholders.
      Usage: It acts as the template string`

`   .param() :This method maps a single dynamic value to a specific placeholder named {k}
    in the template. It substitutes the placeholder **K** with the value **V**
    before the prompt is sent to the **LLM**` */
    @GetMapping("/promptTemplate")
    public String getTemplate(){
        String answer = ChatClient.create(chatModel)
                .prompt()
                .user(u -> u.text("Explain <Topic> in depth").param("Topic", "Kafka"))
                .templateRenderer(StTemplateRenderer.builder().startDelimiterToken('<').endDelimiterToken('>').build())
                .call()
                .content();
        return answer;
    }


    @GetMapping("/userMetadata")
    public String getUserMetadata(){

//        String re = chatClient.prompt()
//                   .user(u ->u.text("Tell about iPhone 16E")
//                        .metadata("messageId", "msg-123")
//                        .metadata("userId", "user-456")
//                        .metadata("priority", "high"))
//                .call()
//                .content();

        // Adding multiple metadata entries at once
        Map<String, Object> userMetadata = Map.of(
                "messageId", "msg-123",
                "userId", "user-456",
                "priority", "high");

        String metaData = chatClient.prompt()
                .user(u -> u.text("Tell about iPhone 16E").metadata(userMetadata))
                .call()
                .content();

        log.info("MetaData :" + userMetadata);
        return metaData;
    }

    @GetMapping("/systemMetadata")
    public String getSystemMetadata(){
        return chatClient.prompt().system(s -> s.text("I am helpful Assistant")
                .metadata("version","1.0")
                .metadata("model","gpt-4"))
                .call()
                .content();
    }



}

